# Production ?? (??? ??? · Android ??)
# ???: main ??? push ?? ?? ??
name: Build Production

on:
  push:
    branches: ['main']
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android (Production)
    type: build
    params:
      platform: android
      profile: production
      message: ${{ github.event.head_commit.message || 'Production build' }}
