# Production ?? ? Play Store ?? (Android ??)
# ???: ?? ??? (workflow_dispatch)
name: Build and Submit to Play Store

on:
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit to Play Store
    type: submit
    needs: [build_android]
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production
