# Preview ?? (?? ???? · Android ??)
# ???: main? ?? ??? push, ?? ?? ??
name: Build Preview

on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android (Preview)
    type: build
    params:
      platform: android
      profile: preview
    env:
      APP_ENV: preview
